config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root 'home#index'

  get '/apply', to: 'playerapp#new'
  post 'apply', to: 'playerapp#create', as: 'playerapps'

  get '/app/:id', to: 'playerapp#show', as: 'playerapp'
  get '/applied', to: 'applied#index'
  get '/admin/apps', to: 'playerapp#index', as: 'apps'
  delete '/admin/app/:id', to: 'playerapp#destroy', as: 'playerapps_delete'

  get '/admin/password', to: 'user#edit', as: 'user_edit'
  patch '/user', to: 'user#update', as: 'user'

  get '/application/:id', to: 'remorseapp#show', as: 'playerapplication'
  get '/admin/applications', to: 'remorseapp#index', as: 'applications'
  
  get '/roster', to: 'roster#index',as: 'roster'
  get '/roster/:id', to: 'roster#show', as: 'member'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/signin" => "clearance/sessions#new", as: "sign_in"
  delete "/signout" => "clearance/sessions#destroy", as: "sign_out"
  get "/signup" => "clearance/users#new", as: "sign_up"


  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    mount Sidekiq::Web, at: '/sidekiq'
  end

  namespace :admin do
    get 'test', to: 'admintest#index'
    get 'frontpage', to: 'frontpage#edit', as: 'frontpage'
    post 'frontpage', to: 'frontpage#update', as: 'frontpage_edit'
    get 'recruitment', to: 'recruitment#index', as: 'recruitment'
    post 'recruitment', to: 'recruitment#update', as: 'recruitment_update'
  end

  scope module: 'api' do
    namespace :v1 do
      get '/recruiting', to: 'recruiting#index'
      get '/backgroundimage',to: 'backgroundimage#index'
      namespace :wow do
        get '/realms', to: 'realms#index'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/remorseapp_controller.rb
class RemorseappController < ApplicationController
  before_action :require_login, only: [:index]

  def index
    @applications = Playerapplication.all
  end

  def show
    return redirect_to root_url unless params.key?(:viewkey)
    @application = Playerapplication.where(id: params[:id], viewkey: params[:viewkey]).first
    redirect_to root_url unless @application
  end
end

app/views/remorseapp/index.html.erb
  <div class="sandbox">
    <div class="tile is-ancestor">
      <div class="tile is-parent">
        <article class="tile is-child notification is-white">
          <div class="content">
            <% @applications.each do |application| %>
              <%= link_to application.player_name, playerapplication_path(application, viewkey: application.viewkey)    %>
              </br><br/>
              Class: <%= application.player_class %> </br>
              Spec: <%= application.player_mainspec %>
              <hr/>
            <% end %>
          </div>
        </article>
      </div>
    </div>
  </div>

app/views/remorseapp/show.html.erb
  <div class="sandbox">
    <div class="tile is-ancestor">
      <div class="tile is-parent">
        <article class="tile is-child notification is-white">
          <div class="content">
            <h2 class="is-size-2"><p>Archived Remorse Application:</p></h2>

            <p><strong>Battle.net:</strong> <%= @application.player_battlenettag %>
            <br>

            <strong>Warcraft Logs:</strong>
            <% @application.links_warcraftlogs.each do |link| %>
              <br/>
              <%= link_to link, link,target: "_blank",rel: "noopener noreferrer"%>
            <% end %>
            <br/>
            <strong>WoW Progress:</strong>
            <% @application.links_wowprogress.each do |link| %> <br/>
              <%= link_to link, link,target: "_blank",rel: "noopener noreferrer" %>
            <% end %>
            </p>
            <p><br/>
            <strong>Name:</strong> <%= @application.player_name %>
            <br>
    <strong>Class:</strong> <%= @application.player_class %>
    <br/><br/>
    </p>
    <p>
    <strong>Main spec:</strong> <%= @application.player_mainspec %>
    <br>  
    <strong>Main spec Artifact Level:</strong> <%= @application.player_mainspec_awt %>
    </p><br/>
    <p>
    <strong>Do you have an offspec? What is its gear like? are you confident in playing your offspec?:</strong>
    </br>
    <%= @application.player_offspec_confidence%>
    </br></br>
    <strong>Do you have any alts?:</strong></br>
    <%= @application.player_alts %>
    </p><p>
    <strong>How do you stay up to date on your class? what sources do you use for theorycrafting?:</strong></br>
    <%= @application.question_theorycraft %>
    </p><br>
    <p>
    <strong>Why you? What makes you unique What will you bring to remorse?:</strong><br>
    <%= @application.question_whyyou %>
    </p>
    <br>
    <p>
    <strong>Why Remorse? What makes you want to join us?:</strong><br>
    <%= @application.question_whyremorse %>
    </p>
    <br>
    <p>
    <strong>Anything else?:</strong><br>
    <%= @application.question_anythingelse %>
    </p><br><br>
          </div>
        </article>
      </div>
    </div>
  </div>