config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root 'home#index'

  get '/apply', to: 'playerapp#new'
  post 'apply', to: 'playerapp#create', as: 'playerapps'

  get '/app/:id', to: 'playerapp#show', as: 'playerapp'
  get '/applied', to: 'applied#index'
  get '/admin/apps', to: 'playerapp#index', as: 'apps'
  delete '/admin/app/:id', to: 'playerapp#destroy', as: 'playerapps_delete'

  get '/admin/password', to: 'user#edit', as: 'user_edit'
  patch '/user', to: 'user#update', as: 'user'

  get '/application/:id', to: 'remorseapp#show', as: 'playerapplication'
  get '/admin/applications', to: 'remorseapp#index', as: 'applications'
  
  get '/roster', to: 'roster#index',as: 'roster'
  get '/roster/:id', to: 'roster#show', as: 'member'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/signin" => "clearance/sessions#new", as: "sign_in"
  delete "/signout" => "clearance/sessions#destroy", as: "sign_out"
  get "/signup" => "clearance/users#new", as: "sign_up"


  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    mount Sidekiq::Web, at: '/sidekiq'
  end

  namespace :admin do
    get 'test', to: 'admintest#index'
    get 'frontpage', to: 'frontpage#edit', as: 'frontpage'
    post 'frontpage', to: 'frontpage#update', as: 'frontpage_edit'
    get 'recruitment', to: 'recruitment#index', as: 'recruitment'
    post 'recruitment', to: 'recruitment#update', as: 'recruitment_update'
  end

  scope module: 'api' do
    namespace :v1 do
      get '/recruiting', to: 'recruiting#index'
      get '/backgroundimage',to: 'backgroundimage#index'
      namespace :wow do
        get '/realms', to: 'realms#index'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/playerapp.rb
class Playerapp < ApplicationRecord
  include Discord
  include Wowarmory
  include Warcraftlogs

  has_many :playerappanswers, dependent: :destroy
  accepts_nested_attributes_for :playerappanswers

  before_create :generate_viewkey
  after_commit :send_to_discord_job

  validates :player_name, presence: true
  validates :player_class, inclusion: { in: %w[Druid Hunter Mage Paladin Priest Rogue Shaman Warlock Warrior DeathKnight Monk DemonHunter] }
  validates :player_spec, presence: true

  def player_links_split
    player_links.split(' / ') unless player_links.nil?
  end

  def link_warcraftlogs
    player_links_split.each do |value|
      return value if value.include? 'warcraftlogs.com'
    end
    'not found'
  end

  def link_raiderio
    player_links_split.each do |value|
      return value if value.include? 'raider.io'
    end
    'not found'
  end

  def link_wowprog
    player_links_split.each do |value|
      return value if value.include? 'wowprogress.com'
    end
    'not found'
  end

  def player_rank(score)
    max_score = ((100 * 11) + 101 + (989 + 15) + 11)
    increase = (max_score - player_rating).to_f
    percent = ((increase / max_score) * 100).to_f.round
    (100 - percent)
  end

  def player_suggestion
    player_score = player_rating
    rank = player_rank(player_score)

    case rank
    when 40..49
      "\nPlayer score: #{player_score} / #{((100 * 11) + 101 + (989 + 15) + 11)}\n" \
      "Rating: __Weak applicant__\n"
    when 50..69
      "\nPlayer score: #{player_score} / #{((100 * 11) + 101 + (989 + 15) + 11)}\n" \
      "Rating: __Good applicant__\n"
    when 70..100
      "\nPlayer score: #{player_score} / #{((100 * 11) + 101 + (989 + 15) + 11)} \n" \
      "Rating: __Strong applicant__\n"
    else
      "\nPlayer score: #{player_score} / #{((100 * 11) + 101 + (989 + 15) + 11)} \n" \
      "Rating: __Bad applicant__\n"
    end
  end

  def player_rating
    total_score = 0
    armory = armory(player_name, player_realm)
    return 0 if armory == false
    log_type = healer?(armory) ? 'hps' : 'dps'
    logs = playerlogs(player_name, player_realm, log_type)
    logs == false ? total_score += 0 : total_score += mythic_parses(logs)
    ilvl = armory['items']['averageItemLevelEquipped'].to_i
    weapon_level = weapon_info(armory['items'], player_spec_is(armory['talents']))
    progression = raid_progression(armory['progression'])
    total_score += (progression + ilvl + weapon_level)
    total_score
  end

  def send_to_discord
    send_to_recruitment_channel(
      "**New application submitted**\n\n" \
      "**Name:** #{player_name}\n" \
      "**Battle.net:** #{player_bnettag}\n" \
      "**Class:** #{player_class}\n" \
      "**Spec:** #{player_spec}\n\n" \
      "**Rating information:** #{player_suggestion}\n\n" \
      "**Logs:** #{link_warcraftlogs}\n" \
      "**WoW Progress:** #{link_wowprog}\n" \
      "**Raider.io:** #{link_raiderio}\n\n" \
      "Click here to view: https://www.isogguild.com/app/#{id}?viewkey=#{viewkey}"
    )
  end

  private

  def send_to_discord_job
    SendToDiscordWorker.perform_async(self.id)
  end

  def generate_viewkey
    self.viewkey = SecureRandom.urlsafe_base64
  end
end

app/controllers/playerapp_controller.rb
class PlayerappController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
  before_action :require_login, only: [:index, :delete]

  def index
    @applications = Playerapp.all.select(:id, :viewkey, :player_name,
                                         :player_class, :player_spec,
                                         :player_links, :player_bnettag)
                             .page(params[:page]).per(5).order(id: 'asc')
  end

  def show
    return redirect_to root_url unless params.key?(:viewkey)
    @application = Playerapp.where(id: params[:id], viewkey: params[:viewkey])
                            .includes(:playerappanswers)
                            .order('playerappanswers.position asc').first
    redirect_to root_url unless @application
  end

  def new
    @recruiting = Setting.find_by(name: 'recruiting').settings
    @questions = Appquestion.where(enabled: true).order('position asc')
    @application = Playerapp.new
  end

  def create
    @application = Playerapp.new(application_params)
    if verify_recaptcha(model: @application, message: 'ReCAPTCHA verification failed') && @application.save
      return render json: { status: 'success' }, status: 201
    else
      return render json: { status: 'ReCAPTCHA failed' }, status: 422
    end
  end

  def destroy
    application = Playerapp.find(params[:id])
    application.destroy!
    flash[:success] = 'Application deleted'
    redirect_to apps_path
  end

  private

  def application_params
    params.require(:playerapp).permit(:player_name, :player_realm,
                                      :player_bnettag,
                                      :player_class, :player_spec, :player_links,
                                      playerappanswers_attributes: [:name, :question, :answer, :position])
  end
end

app/views/playerapp/index.html.erb
  <div class="sandbox">
    <div class="tile is-ancestor">
      <div class="tile is-parent">
        <article class="tile is-child notification is-white">
          <div class="content">
            <% @applications.each do |application| %>
              <%= link_to application.player_name, playerapp_path(application, viewkey: application.viewkey), class: "is-size-4 is-weight-bold" %> 
              </br><br/>
              <h5 class="is-size-6 has-text-weight-bold">Battle.net: <%= application.player_bnettag %> </h5>
              <h5 class="is-size-6 has-text-weight-bold">Class: <%=application.player_class %> </h5> 
              <h5 class="is-size-6 has-text-weight-bold">Spec: <%= application.player_spec %> </h5> </br>
              <h5 class="is-size-6 has-text-weight-bold">Logs: <%= link_to application.link_warcraftlogs, application.link_warcraftlogs %> </h5>
              <h5 class="is-size-6 has-text-weight-bold">WoW Progress: <%= link_to application.link_wowprog, application.link_wowprog %></h5> 
              <h5 class="is-size-6 has-text-weight-bold">Raider.io: <%= link_to application.link_raiderio, application.link_raiderio %> </h5> 
              <div class="has-text-right">
                <%= link_to "Delete", playerapps_delete_path(application), method: :delete, data: { confirm: "You sure?" } %>
              </div>
              <hr/>
          <% end %>
        </article>
        
      </div>
      
    </div>
    
  </div>
<div class="box has-text-centered">
            <nav class="pagination" role="navigation" aria-label="pagination">
          <%= paginate @applications %>
</nav>
 </div>
</div>

app/views/playerapp/new.html.erb
  <div class="sandbox" data-controller="playerapps">
    <div class="tile is-ancestor">
      <div class="tile is-parent">
      <article class="tile is-child notification is-white">
      <div class="content">
            <%= form_with url: '#', id: 'application_form' do |form| %>
                <div class="field">
                    <div class="control">
                        <label class="label app-label">What is your character's name?</label>
                        <input class="input" type="text" name="player_name" id="player_name" data-target="playerapps.name" data-action="input->playerapps#updateLinks" required/>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <label class="label app-label">Realm</label>
                        <div class="select">
                            <select name="player_realm" id="player_realm" data-target="playerapps.realm" data-action="change->playerapps#updateLinks" e></select>
                        </div>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <label class="label app-label">What is your Battle.net tag?</label>
                        <input class="input" type="text" name="player_bnettag" id="player_bnettag" />
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <label class="label app-label">What class are you?</label>
                        <div class="select">
                            <select name="player_class" id="player_class" data-action="change->playerapps#updatespecs" data-target="playerapps.playerspec"></select>
                        </div>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <label class="label app-label">What is your main specialisation?</label>
                        <div class="select">
                            <select name="player_spec" id="player_spec"></select>
                        </div>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <label class="label app-label">Warcraft Logs: <h7 class="is-size-7 is-small app-label"> (click to edit)</h7></label>
                        <input class="input" type="text" name="player_warcraftlogs" id="player_warcraftlogs" data-target="playerapps.wowLogsLink" data-action="click->playerapps#enableWarcraftLogsfield" readonly="readonly" />
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <label class="label app-label">WoW Progress:<h7 class="is-size-7 is-small app-label"> (click to edit)</h7></label>
                        <input class="input" type="text" name="player_wowprogress" id="player_wowprogress" data-target="playerapps.wowProgLink" data-action="click->playerapps#enableWoWProgField" readonly="readonly" />
                    </div>
                </div>
                <% @questions.each do |question| %>
                    <div class="field">
                        <div class="control">
                            <label class="label app-label"><%= question.text %> </label>
                            <% if question.field_type === 'select' %>
                                <div class="select">
                                    <select name="<%= question.text %>" id="<%= question.text %>">></select>
                                </div>
                                <% elsif question.field_type === 'textarea' %>
                                    <textarea class="textarea" name="<%= question.text %>" <%= question.field_options %>></textarea>
                                    <% elsif question.field_type === 'number' %>
                                        <input class="input" type=<%= question.field_type %> name="
                                        <%= question.text %>" id="
                                            <%= question.text %>"
                                                <%= question.field_options %> />
                                                    <% elsif%>
                                                        <input class="input" type=<%=q uestion.field_type %> name="
                                                        <%= question.text %>" id="
                                                            <%= question.text %>"
                                                                <%= question.field_options %> />
                                                                    <% end %>
                        </div>
                    </div>
                    <% end %>
                        <br/>
                        <%= recaptcha_tags(ajax: true)%>
                            <p class="help is-danger recaptcha_warning" id="recaptchaFailed">Recaptcha failed</p>
                            <br/>
                            <div class="control">
                                <button class="button is-info is-outlined" data-action="click->playerapps#submit">Submit</button>
                            </div>
                            <% end %>
                            </divv>
                            </article>
        </div>
        </div>
        </div>
        </div>
</div>

app/views/playerapp/show.html.erb
  <div class="sandbox">
    <div class="tile is-ancestor">
      <div class="tile is-parent">
        <article class="tile is-child notification is-white">
          <div class="content">
            <h1 class="is-size-1 has-text-weight-bold"><%= @application.player_name %> - <%= @application.player_realm  %></h1>
            <h5 class="is-size-6 has-text-weight-bold">Battle.net: <%= @application.player_bnettag %> </h5>
            <h5 class="is-size-6 has-text-weight-bold">Class: <%= @application.player_class %> </h5> 
            <h5 class="is-size-6 has-text-weight-bold">Spec: <%= @application.player_spec %> </h5> 
            <br/>
            <h5 class="is-size-6 has-text-weight-bold">Logs: <%= link_to @application.link_warcraftlogs, @application.link_warcraftlogs %> </h5>
            <h5 class="is-size-6 has-text-weight-bold">WoW Progress: <%= link_to @application.link_wowprog, @application.link_wowprog %></h5> 
            <h5 class="is-size-6 has-text-weight-bold">Raider.io: <%= link_to @application.link_raiderio, @application.link_raiderio %> </h5> 
            <hr/>
            <% @application.playerappanswers.each do |question| %>      
              <h6 class="is-size-6 has-text-weight-bold"><%= question.question %>:</h6>
              <h7 claas="is-size-5 "><%= question.answer %> </h7>
              <br/>
              <br/>
            <% end %>
          </div>
        </article>
      </div>
    </div>
  </div>