config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root 'home#index'

  get '/apply', to: 'playerapp#new'
  post 'apply', to: 'playerapp#create', as: 'playerapps'

  get '/app/:id', to: 'playerapp#show', as: 'playerapp'
  get '/applied', to: 'applied#index'
  get '/admin/apps', to: 'playerapp#index', as: 'apps'
  delete '/admin/app/:id', to: 'playerapp#destroy', as: 'playerapps_delete'

  get '/admin/password', to: 'user#edit', as: 'user_edit'
  patch '/user', to: 'user#update', as: 'user'

  get '/application/:id', to: 'remorseapp#show', as: 'playerapplication'
  get '/admin/applications', to: 'remorseapp#index', as: 'applications'
  
  get '/roster', to: 'roster#index',as: 'roster'
  get '/roster/:id', to: 'roster#show', as: 'member'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/signin" => "clearance/sessions#new", as: "sign_in"
  delete "/signout" => "clearance/sessions#destroy", as: "sign_out"
  get "/signup" => "clearance/users#new", as: "sign_up"


  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    mount Sidekiq::Web, at: '/sidekiq'
  end

  namespace :admin do
    get 'test', to: 'admintest#index'
    get 'frontpage', to: 'frontpage#edit', as: 'frontpage'
    post 'frontpage', to: 'frontpage#update', as: 'frontpage_edit'
    get 'recruitment', to: 'recruitment#index', as: 'recruitment'
    post 'recruitment', to: 'recruitment#update', as: 'recruitment_update'
  end

  scope module: 'api' do
    namespace :v1 do
      get '/recruiting', to: 'recruiting#index'
      get '/backgroundimage',to: 'backgroundimage#index'
      namespace :wow do
        get '/realms', to: 'realms#index'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
    <p class="has-text-centered">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "notification is-#{message_type}") do %>
          <%= message %>
        <% end %>
      <% end %>
    </p>

app/views/layouts/_header.html.erb
<section class="hero is-primary is-large is-bold">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title is-size-1">
        Icky Sticky Ooey Gooey
      </h1>
      <h2 class="subtitle is-size-2">
          Frostmourne | Oceanic
      </h2>
      </div>
      </div>
</section>

app/views/layouts/_navbar.html.erb
    
    <div class="hero-head">
      <nav class="navbar is-fixed-top is-light nav-font">
        <div class="container">
          <div class="navbar-brand">
            <%= link_to '<ISOG>', root_path, class: 'navbar-item is-size-4'%>
            <span class="navbar-burger burger" data-target="navbarMenu">
              <span></span>
              <span></span>
              <span></span>
            </span>
          </div>
          <div id="navbarMenu" class="navbar-menu">
            <div class="navbar-end">
                <%= link_to 'Apply', apply_path, class: 'navbar-item' %>
              <a class="navbar-item" href="https://www.warcraftlogs.com/guilds/253726" target="_blank" rel="noopener noreferrer">
                Guild logs
              </a>
              <a class="navbar-item" href="https://www.wowprogress.com/guild/us/frostmourne/Icky+Sticky+Ooey+Gooey" target="_blank" rel="noopener noreferrer">
                WoW Progress
              </a>
              <a class="navbar-item" href="https://raider.io/guilds/us/frostmourne/Icky%20Sticky%20Ooey%20Gooey" target="_blank" rel="noopener noreferrer">
                raider.io
              </a>
              <% if signed_in? %>
                  <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                    </a>
                      <div class="navbar-dropdown">
                      <%= link_to 'All applications', apps_path, class: 'navbar-item' %>
                      <%= link_to 'Update recruiting', admin_recruitment_path, class: 'navbar-item' %>
                      <%= link_to 'Edit Frontpage', admin_frontpage_edit_path, class: 'navbar-item' %>
                      <hr class="navbar-divider">
                        <%= link_to 'Remorse Applications', applications_path, class: 'navbar-item' %>
                       <hr class="navbar-divider">
                       <%= link_to 'Update password', user_edit_path, class: 'navbar-item' %>
                        <hr class="navbar-divider">
                       <%= link_to 'Logout', sign_out_path, class: 'navbar-item', method: 'delete' %>
                      </div>
                  </div>
                  <% end %>
            </div>
          </div>
        </div>
      </nav>
    </div>

<% if false %> 
    <div class="hero-head">
      <nav class="navbar nav-font" role="navigation" aria-label="dropdown navigation">
        <div class="container">
          <div class="navbar-brand">
            <a class="navbar-item" href="/">
              <img src="<%= asset_pack_path 'images/headerlogo.png' %>" />
            </a>
            <span class="navbar-burger burger" data-target="navbarMenu">
              <span></span>
              <span></span>
              <span></span>
            </span>
          </div>
          <div id="navbarMenu" class="navbar-menu">
            <div class="navbar-end">
             <%= link_to 'Apply', apply_path, class: 'navbar-item' %>
              <a class="navbar-item" href="https://www.warcraftlogs.com/guilds/253726" target="_blank" rel="noopener noreferrer">
                Guild logs
              </a>
              <a class="navbar-item" href="https://www.wowprogress.com/guild/us/frostmourne/Icky+Sticky+Ooey+Gooey" target="_blank" rel="noopener noreferrer">
                WoW Progress
              </a>
              <a class="navbar-item" href="https://raider.io/guilds/us/frostmourne/Icky%20Sticky%20Ooey%20Gooey" target="_blank" rel="noopener noreferrer">
                raider.io
              </a>
              <% if signed_in? %>
                  <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link"></a>
                      <div class="navbar-dropdown">
                      <%= link_to 'All applications', apps_path, class: 'navbar-item' %>
                      <%= link_to 'Update recruiting', admin_recruitment_path, class: 'navbar-item' %>
                      <%= link_to 'Edit Frontpage', admin_frontpage_edit_path, class: 'navbar-item' %>
                      <hr class="navbar-divider">
                        <%= link_to 'Remorse Applications', applications_path, class: 'navbar-item' %>
                       <hr class="navbar-divider">
                       <%= link_to 'Update password', user_edit_path, class: 'navbar-item' %>
                        <hr class="navbar-divider">
                       <%= link_to 'Logout', sign_out_path, class: 'navbar-item', method: 'delete' %>
                      </div>
                  </div>
                  <% end %>
            </div>
          </div>
        </div>
      </nav>
    </div>
    
    <% end %>

app/views/layouts/_progression.html.erb
    <div class="columns features is-centered is-desktop">
      <div class="column is-2">
        <div class="card">
          <div class="card-image has-text-centered">
              <img src="<%= asset_pack_path "images/raid_banner/the-emerald-nightmare.jpg" %>"/>
          </div>
          <div class="card-content">
                <h6 class="has-text-weight-bold is-size"> The Emerald Nightmare </h6> <br/>
                Mythic <progress class="progress is-success is-medium" value="100" max="100" data-label="7/7"></progress>
                Heroic <progress class="progress is-success is-medium" value="100" max="100" data-label="7/7">11/11</progress>
                
   
          </div>
        </div>
      </div>
        <div class="column is-2">
        <div class="card">
          <div class="card-image has-text-centered">
              <img src="<%= asset_pack_path "images/raid_banner/trial-of-valor.jpg" %>"/>
          </div>
          <div class="card-content">
                <h6 class="has-text-weight-bold is-size"> Trial of Valor </h6><br/>
                          </br>
                Mythic <progress class="progress is-success is-medium" value="100" max="100" data-label="3/3"></progress>
                Heroic <progress class="progress is-success is-medium" value="100" max="100" data-label="3/3">11/11</progress>
                
     
          </div>
        </div>
        
      </div>

      <div class="column is-2">
        <div class="card">
          <div class="card-image has-text-centered">
              <img src="<%= asset_pack_path "images/raid_banner/the-nighthold.jpg" %>"/>
          </div>
          <div class="card-content">
                <h6 class="has-text-weight-bold"> The Nighthold </h6><br/>
                           </br>
                Mythic <progress class="progress is-success is-medium" value="100" max="100" data-label="10/10"></progress>
                Heroic <progress class="progress is-success is-medium" value="100" max="100" data-label="10/10">11/11</progress>
                
          </div>

        </div>
      </div>     
            <div class="column is-2">
        <div class="card">
          <div class="card-image has-text-centered">
              <img src="<%= asset_pack_path "images/raid_banner/tomb-of-sargeras.jpg" %>"/>
          </div>
          <div class="card-content">
                <h6 class="has-text-weight-bold"> Tomb of Sargeras</h6>
                          <br/>          <br/>
                Mythic <progress class="progress is-danger is-medium" value="90" max="100" data-label="8/9"></progress>
                Heroic <progress class="progress is-success is-medium" value="100" max="100" data-label="9/9">11/11</progress>

          </div>
          
        </div>
      </div> 
      <div class="column is-2">
        <div class="card">
          <div class="card-image has-text-centered">
              <img src="<%= asset_pack_path "images/raid_banner/antorus-the-burning-throne.jpg" %>"/>
          </div>
          <div class="card-content">
                <h6 class="has-text-weight-bold"> Antrous, The Burning Throne </h6><br/>
                Mythic <progress class="progress is-danger is-medium" value="90" max="100" data-label="10/11"></progress>
                Heroic <progress class="progress is-success is-medium" value="100" max="100" data-label="11/11">11/11</progress>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/_recruiting.html.erb
<% 
  @currently_recruiting = false 
  @currently_recruiting_low_displayed = false
  @currently_recruiting_high_displayed = false
%>

<section class="container has-text-centered">
  <div class="columns features is-centered is-desktop">
    <div class="column is-12">
      <div class="card">
      <br/>
        <h5 class="title is-size-5"> Currently recruiting </h5>
          <div class="class_icons">
            <% @recruiting.each do |cclass ,v| %>
              <% v.each do |spec, vv| %>
                <% if vv == "high" %>
                  <% if !@currently_recruiting_high_displayed %>
                    <h6 class="is-size-6 has-text-weight-bold"> High priority </h6>
                    <% @currently_recruiting_high_displayed = true %>
                  <% end %>
                  <img src="<%= asset_pack_path "images/class_icons/#{cclass}/#{spec}.jpg" %>" class="<%= "#{vv}" %>"/>
                   <% @currently_recruiting = true %>
                <% end %>
              <% end %>   
            <% end %>
            <br/>
            <% @recruiting.each do |cclass ,v| %>
              <% v.each do |spec, vv| %>
                <% if vv == "low" %>
                    <% if !@currently_recruiting_low_displayed %>
                    <h6 class="is-size-6 has-text-weight-bold"> Low priority </h6>
                    <% @currently_recruiting_low_displayed = true %>
                  <% end %>
                  <img src="<%= asset_pack_path "images/class_icons/#{cclass}/#{spec}.jpg" %>" class="<%= "#{vv}" %>"/>
                  <% @currently_recruiting = true%>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <% if !@currently_recruiting %>
            We are not actively recruiting any classes but feel free to submit your application anyway
          <br/>
          <% end %>
          <br/>
        </div>
      </div>
      
    </div>
  </section>

app/views/layouts/application.html.erb
dead

<% if false %>
<!DOCTYPE html>
<html>
  <head>
    <title>Icky Sticky Ooey Gooey | Frostmourne | OCE</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_pack_tag    'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="has-navbar-fixed-top">
    <%= render 'layouts/navbar' %>
    <% if current_page?(root_url) || current_page?(applied_url) %>
      <%= render 'layouts/header'%>
    <% end %>
    <% if current_page?(root_url) || current_page?(apply_path) %>
      <%= render 'layouts/recruiting' %>
    <% end %>
    <section class="container">
      <% if !flash.empty? %>
        <%= render 'layouts/flash' %>
      <% end %>
      <% if current_page?(root_url)  %>
        <%= render 'layouts/progression' %>
      <% end %>
      <%= yield %>
      </section>

  <% if false %>
    <section class="hero is-dark is-fullheight">
    <div class="hero gooey-hero is-fullheight" id="gooey-bg-display">
      <%= render 'layouts/navbar' %>
      <% if !flash.empty? %>
        <%= render 'layouts/flash' %>
      <% end %>
      <%= yield %>
      </div>
    </section>
    <% end %>
  </body>
</html>
<% end %>